server:
  port: 8081

spring:
  application:
    name: gdufe_readingonline
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gdufe_readingonline?useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.gdufe.readingonline.dal.dataobject # 别名扫描包
logging:
  level:
    com.gdufe.readingonline: debug