server:
  port: 8081
  tomcat:
    max-http-post-size: 200MB        # Tomcat POST请求最大大小
    max-http-form-post-size: 200MB   # Tomcat表单POST请求最大大小
    max-connections: 8192            # 最大连接数
    accept-count: 100                # 等待队列长度
    connection-timeout: 20000        # 连接超时时间（毫秒）

spring:
  application:
    name: gdufe_readingonline
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gdufe_readingonline?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root
